version: "3"

tasks:
  pre-commit:
    desc: Run pre-commit checks
    silent: true
    ignore_error: true
    cmds:
      - echo "Starting pre-commit checks..."
      - pre-commit autoupdate || (echo "Failed to autoupdate pre-commit"; exit 1)
      - pre-commit install || (echo "Failed to install pre-commit"; exit 1)
      - pre-commit run --all-files || (echo "Pre-commit checks failed"; exit 1)
      - echo "Pre-commit checks completed successfully"

  gomod-update:
    desc: Update Go modules
    silent: true
    ignore_error: true
    cmds:
      - echo "Updating Go modules..."
      - go get -v -u all && go get -u ./... && go mod tidy || (echo "Go module update failed"; exit 1)
      - echo "Go modules updated successfully"

  gofmt:
    desc: Format Go code
    silent: true
    ignore_error: true
    cmds:
      - echo "Formatting Go code..."
      - go fmt ./... || (echo "go fmt failed"; exit 1)
      - goimports -w . || (echo "goimports failed"; exit 1)
      - echo "Go code formatting completed successfully"

  govet:
    desc: Run Go vet
    silent: true
    cmds:
      - echo "Running Go vet..."
      - go vet -v ./... || (echo "Go vet found issues"; exit 1)
      - echo "Go vet completed successfully"

  golangci-lint:
    desc: Run golangci-lint
    silent: true
    ignore_error: true
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run --out-format colored-line-number || (echo "golangci-lint failed"; exit 1)
      - echo "golangci-lint completed successfully"

  lint-fmt:
    desc: Run all lint and formatting tasks
    silent: true
    ignore_error: true
    cmds:
      - echo "Starting all lint and formatting tasks..."
      - task: pre-commit
      - task: gomod-update
      - task: gofmt
      - task: govet
      - task: golangci-lint
      - echo "All lint and formatting tasks completed successfully"

  all:
    silent: true
    desc: Run the full workflow (lint, format, tag, and push)
    cmds:
      - echo "Starting full workflow..."
      - task: lint-fmt
      - echo "Full workflow completed successfully"
